apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jerney-ebs-sc

provisioner: ebs.csi.eks.amazonaws.com
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"

  # pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jerney-db-pvc
  namespace: jerney
  labels:
    app.kubernetes.io/part-of: jerney
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: jerney-ebs-sc

